// Authentication Action Types

export const GOOGLE_LOGGED_IN = 'GOOGLE_LOGGED_IN';
export const GOOGLE_CLIENT_READY = 'GOOGLE_CLIENT_READY';

export const STEAM_SET_ID = 'STEAM_SET_ID';
export const STEAM_SET_API_KEY = 'STEAM_SET_API_KEY';
export const STEAM_SET_PROFILE = 'STEAM_SET_PROFILE';
export const STEAM_LOGGED = 'STEAM_LOGGED';
export const STEAM_LOAD = 'STEAM_LOAD';
export const STEAM_SET_OWNED_GAMES = 'STEAM_SET_OWNED_GAMES';

export const SPREADSHEET_SET_ID = 'SPREADSHEET_SET_ID';
export const SET_CURRENT_SPREADSHEET_ID = 'SET_CURRENT_SPREADSHEET_ID';
export const SET_CURRENT_SHEET_ID = 'SET_CURRENT_SHEET_ID';
export const SET_UP_COMPLETE = 'SET_UP_COMPLETE';
export const SET_SPREADSHEET_PERMISSION = 'SET_SPREADSHEET_PERMISSION';

// Table Action Types
export const ADD_HEADERS = 'ADD_HEADERS';
export const REMOVE_HEADERS = 'REMOVE_HEADERS';
export const RESET_TABLE_PARAMS = 'RESET_TABLE_PARAMS';
export const RELOAD_TABLE = 'RELOAD_TABLE';
export const CHANGE_ORDER_BY = 'CHANGE_ORDER_BY';
export const CHANGE_PAGE_SIZE = 'CHANGE_PAGE_SIZE';
export const SET_CURRENT_ROWS = 'SET_CURRENT_ROWS';
export const SET_IS_TABLE_EMPTY = 'SET_IS_TABLE_EMPTY';

export const SET_NEW_ROW_CHANGE = 'SET_NEW_ROW';

export const SHOW_SHARE_MODAL = 'SHOW_SHARE_MODAL';

// Import Action Types
export const SET_IMPORTED_HEADERS = 'SET_IMPORTED_HEADERS';
export const SET_IMPORTED_HEADER = 'SET_IMPORTED_HEADER';

// Filters Action Types
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';

// Theme Action Types
export const CHANGE_THEME = 'CHANGE_THEME';