// Authentication Action Types

export const GOOGLE_LOGGED_IN = 'GOOGLE_LOGGED_IN';
export const GOOGLE_CLIENT_READY = 'GOOGLE_CLIENT_READY';

export const STEAM_SET_ID = 'STEAM_SET_ID';
export const STEAM_SET_API_KEY = 'STEAM_SET_API_KEY';
export const STEAM_SET_PROFILE = 'STEAM_SET_PROFILE';
export const STEAM_LOGGED_IN = 'STEAM_LOGGED_IN';
export const STEAM_LOAD = 'STEAM_LOAD';

export const SPREADSHEET_SET_ID = 'SPREADSHEET_SET_ID';
export const SET_UP_COMPLETE = 'SET_UP_COMPLETE';
export const SET_SPREADSHEET_PERMISSION = 'SET_SPREADSHEET_PERMISSION';

// Table Action Types
export const ADD_HEADERS = 'ADD_HEADERS';
export const REMOVE_HEADERS = 'REMOVE_HEADERS';
export const RESET_TABLE_PARAMS = 'RESET_TABLE_PARAMS';
export const RELOAD_TABLE = 'RELOAD_TABLE';
export const CHANGE_ORDER_BY = 'CHANGE_ORDER_BY';
export const CHANGE_PAGE_SIZE = 'CHANGE_PAGE_SIZE';
export const SET_CURRENT_ROWS = 'SET_CURRENT_ROWS';

export const SET_NEW_ROW_CHANGE = 'SET_NEW_ROW';
export const INIT_OPTIONS_CHANGE = 'INIT_OPTIONS_CHANGE';
export const RESET_OPTIONS_CHANGE = 'RESET_OPTIONS_CHANGE';
export const SET_NEW_OPTIONS_CHANGE = 'SET_NEW_OPTIONS';
export const REMOVE_NEW_OPTIONS_CHANGE = 'REMOVE_NEW_OPTIONS_CHANGE';

// Filters Action Types
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';

// Theme Action Types
export const CHANGE_THEME = 'CHANGE_THEME';